### ISSUE TITLE
Container starts, but links dont work -> 404 nginx

### ISSUE THREAD

**Issue by fscorrupt** [chris102994/docker-plutotv#4]
**Error From container log.**

[cont-init.d] 10-display-container-info: exited 0.

[cont-init.d] 40-fix-plutotv-attrs: executing... 

[cont-init.d] 40-fix-plutotv-attrs: exited 0.

[cont-init.d] 50-first-run: executing... 

Traceback (most recent call last):

  File "/app/PlutoTV/PlutoTV/pluto_tv.py", line 322, in <module>

    main()

  File "/app/PlutoTV/PlutoTV/pluto_tv.py", line 318, in main

    ptv.main()

  File "/app/PlutoTV/PlutoTV/pluto_tv.py", line 103, in main

    ptvChannels.Root

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/bindings.py", line 29, in from_bytes

    return self.parse(io.BytesIO(source), clazz)

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/dataclass/parsers/nodes.py", line 446, in parse

    result = handler.parse(source)

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/dataclass/parsers/handlers/native.py", line 47, in parse

    return self.process_context(iterparse(source, EVENTS))  # nosec

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/dataclass/parsers/handlers/native.py", line 61, in process_context

    self.start_ns_bulk(self.ns_map),

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/dataclass/parsers/xml.py", line 57, in start

    super().start(clazz, queue, objects, qname, attrs, ns_map)

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/dataclass/parsers/nodes.py", line 478, in start

    child = item.child(qname, attrs, ns_map, len(objects))

  File "/usr/local/lib/python3.6/dist-packages/xsdata/formats/dataclass/parsers/nodes.py", line 109, in child

    raise ParserError(f"Unknown property {self.meta.qname}:{qname}")

xsdata.exceptions.ParserError: Unknown property element:tileGrayScale

[cont-init.d] 50-first-run: exited 1.

[cont-init.d] 60-fix-nginx-config: executing... 

Ensuring proper NGINX configuration.

[cont-init.d] 60-fix-nginx-config: exited 0.

[cont-init.d] done.

[services.d] starting services

[run]: The Package Manager is apt-get

[services.d] done.

[nginx]: Starting . . .

**Comment by chris102994** [comment]
Looks like they possibly updated their API. I hadn't noticed since I don't watch anything on PlutoTV through my server anymore.
